# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.6

env:
  - TOXENV=django18
  - TOXENV=django111
  - TOXENV=django20

matrix:
  exclude:
    - python: 3.6
      env: TOXENV=django18
  include:
    - python: 3.6
      env: TOXENV=quality

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov
